controllers:
    resource: ../src/Controller/
    type: attribute
person_detail:
    path: /user/detail/
    controller: App\Controller\PersonDetailController
spouse_detail:
    path: /user/detail/
    controller: App\Controller\SpouseDetailController