controllers:
    resource: ../src/Controller/
    type: attribute
person_detail:
    path: /person_detail
    controller: App\Controller\PersonDetailController::Person_detail
spouse_detail:
    path: /user/detail/
    controller: App\Controller\SpouseDetailController